Help on class MeanSquaredLogarithmicError in module keras.src.losses.losses:

class MeanSquaredLogarithmicError(LossFunctionWrapper)
 |  MeanSquaredLogarithmicError(reduction='sum_over_batch_size', name='mean_squared_logarithmic_error', dtype=None)
 |
 |  Computes the mean squared logarithmic error between `y_true` & `y_pred`.
 |
 |  Formula:
 |
 |  ```python
 |  loss = mean(square(log(y_true + 1) - log(y_pred + 1)))
 |  ```
 |
 |  Args:
 |      reduction: Type of reduction to apply to the loss. In almost all cases
 |          this should be `"sum_over_batch_size"`. Supported options are
 |          `"sum"`, `"sum_over_batch_size"`, `"mean"`,
 |          `"mean_with_sample_weight"` or `None`. `"sum"` sums the loss,
 |          `"sum_over_batch_size"` and `"mean"` sum the loss and divide by the
 |          sample size, and `"mean_with_sample_weight"` sums the loss and
 |          divides by the sum of the sample weights. `"none"` and `None`
 |          perform no aggregation. Defaults to `"sum_over_batch_size"`.
 |      name: Optional name for the loss instance.
 |      dtype: The dtype of the loss's computations. Defaults to `None`, which
 |          means using `keras.backend.floatx()`. `keras.backend.floatx()` is a
 |          `"float32"` unless set to different value
 |          (via `keras.backend.set_floatx()`). If a `keras.DTypePolicy` is
 |          provided, then the `compute_dtype` will be utilized.
 |
 |  Method resolution order:
 |      MeanSquaredLogarithmicError
 |      LossFunctionWrapper
 |      keras.src.losses.loss.Loss
 |      keras.src.saving.keras_saveable.KerasSaveable
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(
 |    self,
 |    reduction='sum_over_batch_size',
 |    name='mean_squared_logarithmic_error',
 |    dtype=None
 |  )
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  get_config(self)
 |

